<a href="https://colab.research.google.com/github/abhi-vermaji/abhi-vermaji.github.io/blob/main/Tenserflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [7]:
h_c=tf.constant('Hello World')
h_c

<tf.Tensor 'Const:0' shape=() dtype=string>

In [10]:
ts=tf.Session()
print(ts.run(h_c))

b'Hello World'


In [11]:
a=tf.constant(10,tf.int16)
b=tf.constant(5,tf.int16)
add=a+b
sub=a-b
mul=a*b
div=a/b
print(ts.run([add,sub,mul,div]))

[15, 5, 50, 2.0]


In [17]:
s=tf.Variable("This is string",tf.string)
n=tf.Variable(235,tf.int32)
f=tf.Variable(3.14,tf.float32)
init=tf.global_variables_initializer()
ts.run(init)
print(ts.run(s))
print(ts.run(n))
print(ts.run(f))

b'This is string'
235
3.14


In [22]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
add=a+b
sub=a-b
mul=a*b
div=a/b
print(ts.run(add,feed_dict={a:[1,2,0,3],b:[2,3,5,4]}))
print(ts.run(mul,feed_dict={a:[1,2,3],b:[3,4,5]}))
print(ts.run(sub,feed_dict={a:[1,2,3],b:[5,1,6]}))
print(ts.run(div,feed_dict={a:[10,5,1],b:[5,2,6]}))

[3. 5. 5. 7.]
[ 3.  8. 15.]
[-4.  1. -3.]
[2.         2.5        0.16666667]


In [31]:
#work on tensor
rank1_tensor=tf.Variable(['he','is','a','good','boy'],tf.string)
rank2_tensor=tf.Variable([['hello','hi'],['bye','bye'],['km','km']],tf.string)

In [32]:
tf.rank(rank1_tensor)

<tf.Tensor 'Rank_2:0' shape=() dtype=int32>

In [37]:
tf.rank(rank2_tensor)

<tf.Tensor 'Rank_5:0' shape=() dtype=int32>

In [34]:
print(rank1_tensor.shape)

(5,)


In [35]:
print(rank2_tensor.shape)

(3, 2)
